const Apis = {
    register:'/user/register',
    login:'/user/login',
    nodeIndex:'/node/index',
    getSerach:'/node/getSerach',
    nodeBuy:'/node/buy',
    buyLog:'/node/buyLog',
    expire:'/node/expire',
    agent:'/node/agent',
    resetpwdpost:'/user/resetpwd',
    spread:'/user/spread',
    moenryLog:'/user/moenryLog',
    recharge:'/user/recharge',
    pay:'/user/pay',
    details:'/node/details',
    renew:'/node/renew',
    export:'/node/export',
    wxpay:'/wxpay',
    base:'/user/base',
};
export default Apis;